"Nike DBreak-Type";
export const data = [
  {
    id: Math.random(),
    imgSrc: "./images/product/product_1.jpg",
    date: "13 Dec 2022",
    text: "Nike Air Force 1 NDESTRUKT",
    price: 61.49,
    gender: "men",
    category: "shose",
    color: "green",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_2.jpg",
    date: "05 Oct 2022",
    text: "Nike Space Hippie 04",
    price: 56.22,
    gender: "men",
    category: "shose",
    color: "black",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/accessories_3.jpg",
    date: "25 Apr 2022",
    text: "Accessories",
    price: 10.43,
    gender: "women",
    category: "accessories",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_3.jpg",
    date: "28 Apr 2022",
    text: "Nike Air Zoom Pegasus 37 Chaz Bear",
    price: 40.73,
    gender: "women",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/apparel_2.webp",
    date: "25 Apr 2022",
    text: "Apparel",
    price: 50.43,
    gender: "men",
    category: "apparel",
    color: "yellow",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_4.jpg",
    date: "27 Apr 2022",
    text: "Nike Blazer Low 77 Vintage",
    price: 38.36,
    gender: "men",
    category: "shose",
    color: "black",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_5.jpg",
    date: "17 Aug 2022",
    text: "Nike ZoomX SuperRep Surge",
    price: 30.98,
    gender: "men",
    category: "shose",
    color: "yellow",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_6.jpg",
    date: "14 Jun 2022",
    text: "Zoom Freak 2",
    price: 77.25,
    gender: "women",
    category: "shose",
    color: "white",
  },

  {
    id: Math.random(),
    imgSrc: "./images/product/product_7.jpg",
    date: "15 Dec 2022",
    text: "Nike Air Max Zephyr",
    price: 41.43,
    gender: "women",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_8.jpg",
    date: "17 Jul 2022",
    text: "Jordan Delta",
    price: 47.25,
    gender: "men",
    category: "shose",
    color: "lightGreen",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_9.jpg",
    date: "13 Dec 2022",
    text: "Air Jordan XXXV PF",
    price: 37.73,
    gender: "men",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_10.jpg",
    date: "28 Nov 2022",
    text: "Nike Waffle Racer Crater",
    price: 86.58,
    gender: "men",
    category: "shose",
    color: "black",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_11.jpg",
    date: "25 Apr 2022",
    text: "Kyrie 7 EP Sisterhood",
    price: 24.34,
    gender: "men",
    category: "shose",
    color: "black",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_12.jpg",
    date: "05 Apr 2023",
    text: "Nike Air Zoom BB NXT",
    price: 55.62,
    gender: "women",
    category: "shose",
    color: "red",
  },

  {
    id: Math.random(),
    imgSrc: "./images/product/product_13.jpg",
    date: "01 Sep 2022",
    text: "Nike Air Force 1 07 LX",
    price: 71.31,
    gender: "men",
    category: "shose",
    color: "black",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_14.jpg",
    date: "13 Dec 2022",
    text: "Nike Air Force 1 Shadow SE",
    price: 33.13,
    gender: "men",
    category: "shose",
    color: "grenn",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_15.jpg",
    date: "05 Oct 2022",
    text: "Nike Air Zoom Tempo NEXT%",
    price: 37.73,
    gender: "men",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_16.jpg",
    date: "28 Apr 2022",
    text: "Nike DBreak-Type",
    price: 86.0,
    gender: "women",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_17.jpg",
    date: "27 Apr 2022",
    text: "Nike Air Max Up",
    price: 86.58,
    gender: "women",
    category: "shose",
    color: "pink",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_18.jpg",
    date: "17 Aug 2022",
    text: "Nike Air Max 270 React ENG",
    price: 37.73,
    gender: "men",
    category: "shose",
    color: "black",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/apparel_3.webp",
    date: "25 Apr 2022",
    text: "Apparel",
    price: 50.43,
    gender: "men",
    category: "apparel",
    color: "blue",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_19.jpg",
    date: "14 Jun 2022",
    text: "Nike Court Royale",
    price: 86.58,
    gender: "women",
    category: "shose",
    color: "blue",
  },

  {
    id: Math.random(),
    imgSrc: "./images/product/product_20.jpg",
    date: "15 Dec 2022",
    text: "Nike Air Zoom Pegasus 37 Premium",
    price: 38.36,
    gender: "kids",
    category: "shose",
    color: "yellow",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_21.jpg",
    date: "28 Nov 2022",
    text: "Nike React Art3mis",
    price: 47.25,
    gender: "men",
    category: "shose",
    color: "blue",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/accessories_2.jpg",
    date: "25 Apr 2022",
    text: "Accessories",
    price: 30.3,
    gender: "women",
    category: "accessories",
    color: "pink",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_22.jpg",
    date: "25 Apr 2022",
    text: "Nike React Infinity Run Flyknit A.I.R.",
    price: 77.25,
    gender: "kids",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/apparel_1.webp",
    date: "25 Apr 2022",
    text: "Apparel",
    price: 50.43,
    gender: "men",
    category: "apparel",
    color: "green",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_23.jpg",
    date: "28 Nov 2022",
    text: "Nike Air Zoom BB NXT",
    price: 47.25,
    gender: "women",
    category: "shose",
    color: "white",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/product_24.jpg",
    date: "25 Apr 2022",
    text: "Nike DBreak-Type",
    price: 41.43,
    gender: "women",
    category: "shose",
    color: "red",
  },
  {
    id: Math.random(),
    imgSrc: "./images/product/accessories_1.png",
    date: "25 Apr 2022",
    text: "Accessories",
    price: 50.43,
    gender: "women",
    category: "accessories",
    color: "pink",
  },
];
