export const data = [
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon8.jpg",
    date: "13 Dec 2022",
    text: "40 Free Serif Fonts for Digital Designers",
    avatar: "./images/blog/avatar_1.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon7.jpg",
    date: "05 Oct 2022",
    text: "Tesla Cybertruck-inspired camper trailer for Tesla fans who can’t just wait for the truck!",
    avatar: "./images/blog/avatar_2.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon6.jpg",
    date: "28 Apr 2022",
    text: "Designify Agency Landing Page Design",
    avatar: "./images/blog/avatar_3.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon5.jpg",
    date: "27 Apr 2022",
    text: "✨What is Done is Done ✨",
    avatar: "./images/blog/avatar_4.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon4.jpg",
    date: "17 Aug 2022",
    text: "Fresh Prince",
    avatar: "./images/blog/avatar_5.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon3.jpg",
    date: "14 Jun 2022",
    text: "Six Socks Studio",
    avatar: "./images/blog/avatar_6.jpg",
  },

  {
    id: Math.random(),
    imgSrc: "./images/blog/fon2.jpg",
    date: "15 Dec 2022",
    text: "vincenzo de cotiis’ crossing over showcases a research on contamination",
    avatar: "./images/blog/avatar_7.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon1.jpg",
    date: "17 Jul 2022",
    text: "Simple, Great Looking Animations in Your Project | Video Tutorial",
    avatar: "./images/blog/avatar_8.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon8.jpg",
    date: "13 Dec 2022",
    text: "40 Free Serif Fonts for Digital Designers",
    avatar: "./images/blog/avatar_1.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon7.jpg",
    date: "28 Nov 2022",
    text: "Examining the Evolution of the Typical Web Design Client",
    avatar: "./images/blog/avatar_2.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon6.jpg",
    date: "25 Apr 2022",
    text: "Katie Griffin loves making that homey art",
    avatar: "./images/blog/avatar_3.jpg",
  },
  {
    id: Math.random(),
    imgSrc: "./images/blog/fon5.jpg",
    date: "05 Apr 2023",
    text: "The American Dream retold through mid-century railroad graphics",
    avatar: "./images/blog/avatar_4.jpg",
  },

  {
    id: Math.random(),
    imgSrc: "./images/blog/fon4.jpg",
    date: "01 Sep 2022",
    text: "Illustration System Design",
    avatar: "./images/blog/avatar_5.jpg",
  },
];
