export const data = [
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Alfredo Paucek",
    company: "Parisian, Schmitt and Christiansen",
    role: "Backend Developer",
    verified: "No",
    status: "Banned",
    completed: false,
  },
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Amanda Yost",
    company: "Ritchie, Haley and Botsford",
    role: "Leader",
    verified: "Yes",
    status: "Active",
    completed: false,
  },
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Alfredo Paucek",
    company: "Parisian, Schmitt and Christiansen",
    role: "Backend Developer",
    verified: "No",
    status: "Banned",
    completed: false,
  },
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Benjamin Jacobs",
    company: "Stanton - Beier",
    role: "Full Stack Developer",
    verified: "Yes",
    status: "Active",
    completed: false,
  },
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Dan Wilderman",
    company: "Conn - Stehr",
    role: "Project Manager",
    verified: "No",
    status: "Active",
    completed: false,
  },
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Tommie Bechtelar",
    company: "Durgan - Stoltenberg",
    role: "Full Stack Designer",
    verified: "No",
    status: "Banned",
    completed: false,
  },
  {
    id: Math.random(),
    imgSrc: "./images/avatar.jpg",
    name: "Edna Gleason",
    company: "Schowalter, Lehner and Doyle",
    role: "Backend Developer",
    verified: "No",
    status: "Banned",
    completed: false,
  },
];
